version: '3.8'

services:
  backend:
    build: ./backend
    container_name: laravel-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/storage:/var/www/storage
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
